docs/DeveloperGuide.md
docs/UserGuide.md
docs/index.md
docs/team/kxrt.md

- Update Developer Guide glossary to include hospital staff/administrator.
- Update User Guide to include `count`, and standardise references of `person(s)` to `patient(s)`.
- Update CI Status and CodeCov badges in `index.md`.
- Update `index.md` to replace AB3 details with checkUp.
- Update PPP with contribution details.

Update project documentation

---

src/main/java/seedu/address/logic/commands/GetInpatientCommand.java
src/main/java/seedu/address/logic/commands/GetOutpatientCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/model/person/PatientTypePredicate.java

Implemented get /inp to get a list of all inpatients and get /outp to get a list of outpatients.

Add get /inp and get /outp

---

src/main/java/seedu/address/logic/commands/GetHospitalWingCommand.java
src/main/java/seedu/address/model/Model.java

Currently it takes into account outpatients which are not assigned a hospital wing.
Also resolves the Invocation Target Error.

Modify get /hw feature

---

README.md

Add CodeCov badge to README

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/GetCommand.java
src/main/java/seedu/address/logic/commands/getcommands/GetFloorNumberCommand.java
src/main/java/seedu/address/logic/commands/getcommands/GetHospitalWingCommand.java
src/main/java/seedu/address/logic/commands/getcommands/GetInpatientCommand.java
src/main/java/seedu/address/logic/commands/getcommands/GetOutpatientCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/GetCommandParser.java
src/main/java/seedu/address/logic/parser/getparsers/GetFloorNumberParser.java
src/main/java/seedu/address/logic/parser/getparsers/GetHospitalWingCommandParser.java

Moved all previously implemented get commands
- `GetInpatientCommand`
- `GetOutpatientCommand`
- `GetFloorNumberCommand`
- `GetHospitalWingCommand`
into `GetCommand` superclass.

Redo GetCommand logic

---

docs/AboutUs.md

Update responsibilities in AboutUs

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/getparsers/GetWardNumberCommandParser.java
src/main/java/seedu/address/model/person/WardNumber.java
src/main/java/seedu/address/model/person/WardNumberPredicate.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Ward Number can now only be stored as **ONE** alphabet followed by 3 numbers.
Close #63.

Implement restrictions on WardNumber

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/getcommands/GetMedicationCommand.java
src/main/java/seedu/address/logic/parser/GetCommandParser.java
src/main/java/seedu/address/logic/parser/getparsers/GetMedicationCommandParser.java
src/main/java/seedu/address/model/person/MedicationContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

Feature implemented: Filters out list of patients that are on the specific query medication.
Eg. `get /m paracetamol` shows a list of patients currently administered "paracetamol".
Close #8.

Implement get /m feature

---

src/main/java/seedu/address/logic/commands/getcommands/GetAppointmentByDateCommand.java
src/main/java/seedu/address/logic/commands/getcommands/GetHospitalWingCommand.java
src/main/java/seedu/address/logic/parser/GetCommandParser.java
src/main/java/seedu/address/logic/parser/getparsers/GetAppointmentByDateCommandParser.java
src/main/java/seedu/address/model/appointment/PastAppointment.java
src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
src/main/java/seedu/address/model/person/AppointmentByDatePredicate.java
src/main/java/seedu/address/model/person/HospitalWingContainsKeywordsPredicate.java

Command format:
`get /apptbd [DATE]`
Example:
`get /apptbd 21-12-2002`

Implement get appointment by date feature

---

src/main/java/seedu/address/logic/commands/getcommands/GetPastAppointmentCommand.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/MainWindow.fxml

Rearrange GUI for detailed person card.
Adjusted the usage message for get /appt.

Rearrange GUI to give space for detailed person card

---

src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/model/appointment/PastAppointment.java
src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
src/main/java/seedu/address/model/person/AppointmentByDatePredicate.java
src/main/java/seedu/address/model/person/Person.java
src/main/resources/view/MainWindow.fxml
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/CreatePastAppointmentCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/getcommands/GetAppointmentByDateCommandTest.java
src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Command input and output windows have been shifted to the bottom of the UI.
Closes #104

Shift command I/O in UI down, add unit tests for past appointments

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/CreatePastAppointmentCommandParser.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/appointment/Appointment.java
src/main/java/seedu/address/model/appointment/PastAppointment.java
src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/resources/view/CountWindow.fxml
src/main/resources/view/PersonViewPanel.fxml
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/testutil/TypicalPersons.java

AddCommand now supports the upcoming appointment field.
UpcomingAppointment now rejects dates before today and vice versa for PastAppointment

Improve AddCommand Capabilities and Fix Appointment Bug

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/ConsultCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ConsultCommandParser.java
src/main/java/seedu/address/logic/parser/DeletePastAppointmentCommandParser.java
src/main/java/seedu/address/ui/CommandBox.java

consult feature combines appt and editing the upcoming appointment. creates a past appointment for today's date, and if the upcoming appointment is today, it consumes it.

Add Consult Command

---

docs/UserGuide.md
docs/team/kxrt.md

The command descriptions for the `Add`, `Edit` and `Appt` commands in the UG are very messy and hard to read. These lists will make it easier for readers to understand our requirements.
Closes #177

Add parameter lists

---

docs/UserGuide.md

Did a run through to correct:
- Vocabulary and grammatical issues
- Sentence structure for simplification
- Formatting issues

Complete cleaning of UG

---

docs/UserGuide.md

Fix UG formatting issues

---

src/main/java/seedu/address/logic/commands/ConsultCommand.java
src/main/java/seedu/address/logic/parser/CreatePastAppointmentCommandParser.java
src/main/java/seedu/address/logic/parser/getparsers/GetAppointmentByDateCommandParser.java
src/main/java/seedu/address/model/appointment/Appointment.java
src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
src/main/java/seedu/address/model/person/HospitalWing.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPastAppointment.java
src/test/java/seedu/address/model/appointment/AppointmentTest.java
src/test/java/seedu/address/model/util/SampleDataUtilTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PastAppointmentBuilder.java
src/test/java/seedu/address/testutil/PersonBuilder.java

- [Fix text duplication bug on printing person](https://github.com/AY2223S1-CS2103T-W16-3/tp/commit/51e4e76e25803634bc1ec5a1033273acaefbd325) - Fixes #140 
- [Fix incorrect Optional::get calls](https://github.com/AY2223S1-CS2103T-W16-3/tp/commit/a57578d4cf88354902d3fb4b88429258d61ea3ae)
- [Enable stricter parsing to catch non-existent dates](https://github.com/AY2223S1-CS2103T-W16-3/tp/commit/6cd51b25e5b4ab25b736c71cb5dabcf0f94cc5ad) - Fixes #147, Fixes #176
- [Add tests for Appointment::isValidDate changes, update dates to dd-MM-uuuu](https://github.com/AY2223S1-CS2103T-W16-3/tp/commit/9cbf20b5a6ee21523df7e1cbe2611184b6a9fad8)

Fix incorrect text displayed and date parsing

---

docs/UserGuide.md

Make introduction more user friendly.
Adds installation guide.
Adds troubleshooting section.

Edits user guide

---

src/main/java/seedu/address/logic/commands/DeletePastAppointmentCommand.java
src/test/java/seedu/address/logic/commands/DeletePastAppointmentCommandTest.java
src/test/java/seedu/address/logic/commands/getcommands/GetFloorNumberCommandTest.java
src/test/java/seedu/address/logic/commands/getcommands/GetPastAppointmentCommandTest.java
src/test/java/seedu/address/logic/parser/DeletePastAppointmentCommandParserTest.java
src/test/java/seedu/address/logic/parser/GetCommandParserTest.java
src/test/java/seedu/address/logic/parser/getparsers/GetFloorNumberCommandParserTest.java
src/test/java/seedu/address/logic/parser/getparsers/GetMedicationCommandParserTest.java
src/test/java/seedu/address/logic/parser/getparsers/GetNameCommandParserTest.java
src/test/java/seedu/address/logic/parser/getparsers/GetPastAppointmentCommandParserTest.java
src/test/java/seedu/address/model/person/FloorNumberTest.java
src/test/java/seedu/address/model/person/HospitalWingTest.java
src/test/java/seedu/address/model/person/NameTest.java
src/test/java/seedu/address/model/tag/MedicationTest.java

Implement more testcases 

---

docs/DeveloperGuide.md

for `get /appton` and `get /hw`

Adds manual testing

---

src/main/java/seedu/address/logic/commands/ConsultCommand.java
src/main/java/seedu/address/model/person/NextOfKin.java
src/test/java/seedu/address/logic/parser/getparsers/GetAppointmentByDateCommandParserTest.java

Edits test cases

---

docs/team/peiyee88.md

Updates PPP details

---

docs/UserGuide.md

Updates user guide

---

docs/UserGuide.md

- Add specification of date requirements to be in the past/future
- Add explanation of data rejection

Update UG wording
